version: '3'

services:
  eventstore:
    image: eventstore/eventstore:20.10.5-buster-slim
    environment:
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=True
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_RUN_PROJECTIONS=${EVENTSTORE_RUN_PROJECTIONS:-None}
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=${EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP:-True}
    ports:
      - 1113:1113
      - 2113:2113
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.19.0
    command:
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=30d
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.enable-admin-api
    volumes:
      - ../common/prometheus-config:/etc/prometheus/
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.5.2
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000

  grafana-init:
    image: alpine:3.13
    depends_on:
      - grafana
    volumes:
      - ../common/init:/root/init/
    command: sh -c "chmod +x /root/init/grafana-init.sh && sh /root/init/grafana-init.sh"

volumes:
  grafana-volume:
