GET http://localhost:2113/stats
Authorization: Basic YWRtaW46Y2hhbmdlaXQ=

###

GET http://localhost:2113/projections/all-non-transient
Authorization: Basic YWRtaW46Y2hhbmdlaXQ=

###

GET http://localhost:2113/info
Authorization: Basic YWRtaW46Y2hhbmdlaXQ=

###

GET http://localhost:2113/subscriptions
Authorization: Basic YWRtaW46Y2hhbmdlaXQ=

